apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev_ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev_ops
  template:
    metadata:
      labels:
        app: dev_ops
    spec:
      containers:
        - name: dev_ops
          image: st1lson/dev_ops
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health-check
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 2
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          resources:
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: /etc/nginx
            readOnly: true
            name: nginx-conf
          - mountPath: /var/log/nginx
            name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: virtualhost.conf
                path: virtualhost/virtualhost.conf
        - name: log
          emptyDir: {}