name: Analyzer
on:
  push:
    branches: [ci-cd, main]
  pull_request:
    branches: [ci-cd, main]
jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install packages
        run: |
          npm ci
        
      - name: Run linter and prettier
        run: |
          npm run lint
          npm run format:check

  build-image:
    needs: clean-up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_PROFILE }}/dev_ops:latest
          outputs: type=docker,dest=/tmp/dev_ops.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dev_ops
          path: /tmp/dev_ops.tar

  push-image:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dev_ops
          path: /tmp
        
      - name: Login DockerHub account
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_PROFILE }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Load Docker image
        run: |
          docker load --input /tmp/dev_ops.tar
        
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_PROFILE }}/dev_ops
        
  run-image:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub account
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_PROFILE }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Pull image
        run: |
          docker pull ${{ secrets.DOCKERHUB_PROFILE }}/dev_ops
        
      - name: Run image
        run: |
          docker run -p 80:80 -d ${{ secrets.DOCKERHUB_PROFILE }}/dev_ops
          docker container ls
      
      - name: Curl check
        run: |
          sleep 5;
          curl localhost:80
